# Source: https://github.com/pvinis/react-native-xcodegen/blob/master/templates/project-0.63.3.yml

name: Eventer

options:
    deploymentTarget:
        iOS: "12.4"
    usesTabs: false
    tabWidth: 2
    indentWidth: 2
    defaultConfig: Release

fileGroups:
    - main.jsbundle

settings:
    base:
        LD_RUNPATH_SEARCH_PATHS:
            - /usr/lib/swift
            - $(inherited)
        LIBRARY_SEARCH_PATHS:
            - $(TOOLCHAIN_DIR)/usr/lib/swift/$(PLATFORM_NAME)
            - $(TOOLCHAIN_DIR)/usr/lib/swift-5.0/$(PLATFORM_NAME)
            - $(inherited)
        CLANG_ANALYZER_LOCALIZABILITY_NONLOCALIZED: true
        GCC_C_LANGUAGE_STANDARD: gnu99
        CLANG_CXX_LANGUAGE_STANDARD: gnu++0x
    configs:
        Debug:
            COPY_PHASE_STRIP: false
            GCC_SYMBOLS_PRIVATE_EXTERN: false
            MTL_ENABLE_DEBUG_INFO: true
        Release:
            COPY_PHASE_STRIP: true
            MTL_ENABLE_DEBUG_INFO: false

targets:
    Eventer:
        type: application
        platform: iOS
        sources:
            - Eventer
        dependencies:
            - framework: JavascriptCore.framework
              embed: false
              link: false
        scheme:
            parallelizeBuild: false
        settings:
            base:
                CODE_SIGN_ENTITLEMENTS: Eventer/Eventer.entitlements
                PRODUCT_BUNDLE_IDENTIFIER: "${BUNDLE_IDENT}"
                CLANG_ENABLE_MODULES: true
                EXCLUDED_ARCHS[sdk=iphonesimulator*]: arm64
                OTHER_LDFLAGS:
                    - $(inherited)
                    - -ObjC
                    - -lc++
            configs:
                Debug:
                    ENABLE_BITCODE: false
                    GCC_PREPROCESSOR_DEFINITIONS:
                        - $(inherited)
                        - FB_SONARKIT_ENABLED=1
        attributes:
            SystemCapabilities:
                com.apple.Push:
                    enabled: 1
        preBuildScripts:
            - name: Start Packager
              script: |
                  export RCT_METRO_PORT="${RCT_METRO_PORT:=8081}"
                  echo "export RCT_METRO_PORT=${RCT_METRO_PORT}" > "${SRCROOT}/../node_modules/react-native/scripts/.packager.env"
                  if [ -z "${RCT_NO_LAUNCH_PACKAGER+xxx}" ] ; then
                    if nc -w 5 -z localhost ${RCT_METRO_PORT} ; then
                      if ! curl -s "http://localhost:${RCT_METRO_PORT}/status" | grep -q "packager-status:running" ; then
                        echo "Port ${RCT_METRO_PORT} already in use, packager is either not running or not running correctly"
                        exit 2
                      fi
                    else
                      open "$SRCROOT/../node_modules/react-native/scripts/launchPackager.command" || echo "Can't start packager automatically"
                    fi
                  fi
              showEnvVars: false
        postBuildScripts:
            - name: Bundle React Native code and images
              script: |
                  export NODE_BINARY=node
                  ../node_modules/react-native/scripts/react-native-xcode.sh
    EventerTests:
        type: bundle.unit-test
        platform: iOS
        sources:
            - EventerTests
