name: Build & Test Backend

on: [push]

jobs:
  build_backend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Go environment
        uses: actions/setup-go@v2.1.4
        with:
          go-version: "^1.19.4"
      - name: Run tests
        run: go test ./internal/...
      - name: Build Application
        run: PATH="$PATH:$HOME/go/bin" ./scripts/build.sh
