name: Build Frontend

on: [push]

jobs:
  build_npm:
    runs-on: ubuntu-latest

    env:
      frontend-dir: ./frontend

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3.1.0
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
        working-directory: ${{ env.frontend-dir }}
      - name: Build (typecheck) the project
        run: npm run typecheck
        working-directory: ${{ env.frontend-dir }}
      - name: Lint the project
        run: npm run lint
        working-directory: ${{ env.frontend-dir }}
      - name: Run the tests
        run: npm test
        working-directory: ${{ env.frontend-dir }}
