name: Docker

on:
  workflow_run:
    workflows:
      - Build & Test Frontend
      - Build & Test Backend
    types:
      - completed

jobs:
  publish-docker-image:
    name: Build & Publish Docker Image
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    env:
      frontend-dir: ./frontend

    steps:
      - uses: actions/checkout@v2

      - name: Setup Go environment
        uses: actions/setup-go@v2.1.4
        with:
          go-version: "^1.19.4"
      - name: Build Backend
        run: PESCA_RELEASE=1 ./scripts/build.sh

      - name: Set up Node.js
        uses: actions/setup-node@v3.1.0
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
        working-directory: ${{ env.frontend-dir }}
      - name: Build Frontend
        run: npm run build:web
        working-directory: ${{ env.frontend-dir }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_PAT }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/${{ env.OWNER_LC }}/eventer:latest
