name: iOS

on: [push]

jobs:
  build_ios:
    name: Build iOS App
    runs-on: macos-11

    env:
      frontend-dir: ./frontend

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3.1.0
        with:
          node-version: ${{ matrix.node-version }}

      - name: Restore Pods cache
        uses: actions/cache@v2
        with:
          path: ${{ env.frontend-dir }}/.local_derived_data
          key: ${{ runner.os }}-pods-derived-data-${{ hashFiles('frontend/ios/Podfile.lock') }}

      - name: Set up environment (dependencies, Xcode project)
        run: scripts/setup --ios --ci
        working-directory: ${{ env.frontend-dir }}
      - name: Build the app
        run: bundle exec fastlane build_cached
        working-directory: ${{ env.frontend-dir }}/ios
