name: K8s

on:
  workflow_run:
    workflows:
      - Docker
    types:
      - completed

jobs:
  deploy-on-cluster:
    name: Deploy On Cluster
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set lower case owner name
        run: |
          echo "OWNER_LC=${OWNER,,}" >>${GITHUB_ENV}
        env:
          OWNER: "${{ github.repository_owner }}"

      - uses: azure/k8s-set-context@v2
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.K8S_CONFIG }}
      - uses: Azure/k8s-deploy@v1.4
        with:
          manifests: |
            k8s/eventer.yml
          images: |
            ghcr.io/${{ env.OWNER_LC }}/eventer:${{ github.sha }}
          kubectl-version: "latest"
          namespace: eventer
