name: Test Backend

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Go environment
        uses: actions/setup-go@v2
        with:
          go-version: "^1.19.4"
      - name: Update packages
        run: sudo apt update
      - name: Run tests
        run: go test ./internal/...
